export interface ErrorType {
  type: string;
  code: number;
}

export const ErrorTypes = {
  CONFLICT_ERROR: "CONFLICT_ERROR",
  UNAUTHORIZED_ERROR: "UNAUTHORIZED_ERROR",
  NOT_FOUND_ERROR: "NOT_FOUND_ERROR",
  FORBIDDEN_ERROR: "FORBIDDEN_ERROR",
  BAD_REQUEST_ERROR: "BAD_REQUEST_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNPROCESSABLE_ENTITY: "UNPROCESSABLE_ENTITY",
  MISSING_TOKEN: "MISSING_TOKEN",
  INVALID_TOKEN: "INVALID_TOKEN",
};

